### ISSUE TITLE
Path to AtlasSiteConfig.yaml and ArrayExpressSiteConfig.yaml should be overridable through env var

### ISSUE THREAD

**Issue by pcm32** [ebi-gene-expression-group/perl-atlas-modules#6]
Currently lower level perl modules (Common.pm) work out the location of the site config files to a place inside the conda environment installation. For greater flexibility for the user, there should be an env variable, say PATH_ATLAS_SITE_CONFIG that when set makes the underlying perl modules to load the yaml file from that location instead, so that the user can have its config files separate from the conda package (the same for the ArrayExpressSiteConfig one).

**Comment by pcm32** [comment]
It should probably happen at this point https://github.com/ebi-gene-expression-group/perl-atlas-modules/blob/develop/perl_modules/Atlas/Common.pm#L99 (setting and env var for the directory rather than the actual file).

**Comment by anjaf** [comment]
This has been solved here: https://github.com/ebi-gene-expression-group/perl-atlas-modules/pull/17
